import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import Ajv2020 from "ajv/dist/2020.js";
import { describe, expect, it } from "vitest";

import {
  BPF_UPGRADEABLE_LOADER_ID,
  WHITELIST_CONFIG_PDA,
  WHITELIST_PROGRAM_ID,
  assertPublicKey,
  assertRpcUrl,
  decodeProgramAccount,
  decodeProgramDataAccount,
  decodeWhitelistConfig,
  encodeBase58,
  JsonRpcClient,
  sanitizeRpcOrigin,
  verifyManifestAccounts,
} from "../../scripts/deployment-verifier.mjs";

const BASKET_PROGRAM_ID = "6Q43vFh4aqGxzvtU2vQwJX9PmX3skfYsGWZdA3fwJB9k";
const FACTORY_PROGRAM_ID = "3hzoPep9JKgTmzLT6CNW5x3EN7WNYDevM6KHVM7pLgMF";
const EXPECTED_AUTHORITY = "y72KA263br7MtZw7BqC2dx5QYCBUciJGzShE8BRSwRE";
const MANIFEST_SHA256 = "ab".repeat(32);
const evidenceSchema = JSON.parse(readFileSync(
  new URL("../../deploy/deployment-verification.schema.json", import.meta.url),
  "utf8",
));
const validateEvidence = new Ajv2020({
  allErrors: true,
  strict: true,
  formats: { "date-time": true, uri: true },
}).compile(evidenceSchema);

function key(seed: number): string {
  return encodeBase58(Uint8Array.from({ length: 32 }, (_, index) => (seed + index) & 0xff));
}

function u32(value: number): Uint8Array {
  const bytes = new Uint8Array(4);
  new DataView(bytes.buffer).setUint32(0, value, true);
  return bytes;
}

function u64(value: bigint): Uint8Array {
  const bytes = new Uint8Array(8);
  new DataView(bytes.buffer).setBigUint64(0, value, true);
  return bytes;
}

function concat(...parts: Uint8Array[]): Uint8Array {
  const output = new Uint8Array(parts.reduce((total, part) => total + part.length, 0));
  let offset = 0;
  for (const part of parts) {
    output.set(part, offset);
    offset += part.length;
  }
  return output;
}

function pubkeyBytes(value: string): Uint8Array {
  // The fixtures use public keys generated by key(), whose byte representation
  // is intentionally deterministic and easy to embed in account data.
  const alphabet = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
  const index = new Map([...alphabet].map((character, position) => [character, BigInt(position)]));
  let number = 0n;
  for (const character of value) number = number * 58n + (index.get(character) ?? 0n);
  const bytes: number[] = [];
  while (number > 0n) {
    bytes.push(Number(number & 0xffn));
    number >>= 8n;
  }
  for (const character of value) {
    if (character !== "1") break;
    bytes.push(0);
  }
  bytes.reverse();
  return Uint8Array.from(bytes);
}

function account(data: Uint8Array, owner: string, executable: boolean) {
  return {
    owner,
    executable,
    data: [Buffer.from(data).toString("base64"), "base64"],
  };
}

function programDataAccount(address: string, slot: bigint, authority: string = EXPECTED_AUTHORITY) {
  const header = concat(u32(3), u64(slot), Uint8Array.of(1), pubkeyBytes(authority));
  return { address, account: account(concat(header, Uint8Array.of(0x7f, 0x45, 0x4c, 0x46)), BPF_UPGRADEABLE_LOADER_ID, false) };
}

function whitelistConfigAccount(authority: string = EXPECTED_AUTHORITY, pending: string | null = null) {
  const discriminator = createHash("sha256").update("account:WhitelistConfig").digest().subarray(0, 8);
  const authorityBytes = pubkeyBytes(authority);
  const pendingBytes = pending === null ? Uint8Array.of(0) : concat(Uint8Array.of(1), pubkeyBytes(pending));
  const data = concat(discriminator, authorityBytes, pendingBytes, new Uint8Array(4 + 1));
  return account(data, WHITELIST_PROGRAM_ID, false);
}

function fixtureManifest() {
  return {
    schemaVersion: 2,
    project: "basalt",
    git: { commit: "a".repeat(40) },
    deployment: {
      environment: "devnet",
      cluster: "devnet",
      rpcUrl: null,
      deployedSlot: null,
    },
    programs: {
      basket: { programId: BASKET_PROGRAM_ID, upgradeAuthority: null, deployedSlot: null },
      basket_factory: { programId: FACTORY_PROGRAM_ID, upgradeAuthority: null, deployedSlot: null },
      whitelist: { programId: WHITELIST_PROGRAM_ID, upgradeAuthority: null, deployedSlot: null },
    },
  };
}

function makeRpcFixture({ authority = EXPECTED_AUTHORITY, programAuthority = authority, pending = null } = {}) {
  const programData = {
    basket: key(41),
    basket_factory: key(81),
    whitelist: key(121),
  };
  const addressesByProgram = new Map([
    [BASKET_PROGRAM_ID, programData.basket],
    [FACTORY_PROGRAM_ID, programData.basket_factory],
    [WHITELIST_PROGRAM_ID, programData.whitelist],
  ]);
  const slots = {
    basket: 2n ** 64n - 1n,
    basket_factory: 493110824n,
    whitelist: 493110585n,
  };
  const namesByProgram = new Map([
    [BASKET_PROGRAM_ID, "basket"],
    [FACTORY_PROGRAM_ID, "basket_factory"],
    [WHITELIST_PROGRAM_ID, "whitelist"],
  ]);
  const calls: Array<{ method: string; params: unknown[] }> = [];
  const fetchImpl = async (_url: string, options: { body: string }) => {
    const request = JSON.parse(options.body) as { method: string; params: unknown[]; id: number };
    calls.push(request);
    if (request.method !== "getMultipleAccounts") {
      return {
        ok: true,
        status: 200,
        json: async () => ({ jsonrpc: "2.0", id: request.id, result: null }),
      };
    }
    const addresses = request.params[0] as string[];
    const values = addresses.map((address) => {
      const name = namesByProgram.get(address);
      if (name) {
        const programDataAddress = addressesByProgram.get(address)!;
        return account(concat(u32(2), pubkeyBytes(programDataAddress)), BPF_UPGRADEABLE_LOADER_ID, true);
      }
      if (address === WHITELIST_CONFIG_PDA) return whitelistConfigAccount(authority, pending);
      const nameForData = Object.entries(programData).find(([, value]) => value === address)?.[0] as keyof typeof slots | undefined;
      if (!nameForData) return null;
      return programDataAccount(address, slots[nameForData], programAuthority).account;
    });
    const contextSlot = calls.length === 1 ? 900n : 901n;
    return {
      ok: true,
      status: 200,
      json: async () => ({
        jsonrpc: "2.0",
        id: request.id,
        result: { context: { slot: Number(contextSlot) }, value: values },
      }),
    };
  };
  return { fetchImpl, calls, programData, slots };
}

describe("deployment verifier binary parsers", () => {
  it("parses the exact 36-byte upgradeable Program account", () => {
    const programData = key(9);
    expect(decodeProgramAccount(concat(u32(2), pubkeyBytes(programData)))).toEqual({
      stateTag: 2,
      programDataAddress: programData,
    });
    expect(() => decodeProgramAccount(new Uint8Array(35))).toThrow("exactly 36 bytes");
    expect(() => decodeProgramAccount(concat(u32(3), pubkeyBytes(programData)))).toThrow("tag 2");
  });

  it("parses ProgramData Some authority with a 45-byte header", () => {
    const decoded = decodeProgramDataAccount(concat(
      u32(3),
      u64(2n ** 64n - 1n),
      Uint8Array.of(1),
      pubkeyBytes(EXPECTED_AUTHORITY),
      Uint8Array.of(0x7f, 0x45, 0x4c, 0x46),
    ));
    expect(decoded).toMatchObject({
      stateTag: 3,
      slot: "18446744073709551615",
      upgradeAuthority: EXPECTED_AUTHORITY,
      authorityOption: 1,
      metadataLength: 45,
      programDataLength: 4,
    });
  });

  it("parses immutable ProgramData with the loader's padded 45-byte metadata and rejects malformed options", () => {
    expect(decodeProgramDataAccount(concat(u32(3), u64(17n), new Uint8Array(33), Uint8Array.of(1)))).toMatchObject({
      slot: "17",
      upgradeAuthority: null,
      metadataLength: 45,
      programDataLength: 1,
    });
    expect(() => decodeProgramDataAccount(concat(u32(3), u64(17n), Uint8Array.of(2), new Uint8Array(32)))).toThrow("0 or 1");
    expect(() => decodeProgramDataAccount(concat(u32(3), u64(17n), Uint8Array.of(1)))).toThrow("45-byte metadata");
  });

  it("decodes WhitelistConfig authority and pending authority", () => {
    const clean = decodeWhitelistConfig(Buffer.from(whitelistConfigAccount().data[0], "base64"));
    expect(clean).toEqual({ authority: EXPECTED_AUTHORITY, pendingAuthority: null, pendingOption: 0 });
    const pending = key(221);
    const pendingDecoded = decodeWhitelistConfig(Buffer.from(whitelistConfigAccount(EXPECTED_AUTHORITY, pending).data[0], "base64"));
    expect(pendingDecoded.pendingAuthority).toBe(pending);
  });
});

describe("deployment verifier RPC evidence", () => {
  it("reads only finalized getMultipleAccounts and emits sanitized RPC evidence", async () => {
    const fixture = makeRpcFixture();
    const evidence = await verifyManifestAccounts({
      manifest: fixtureManifest(),
      sourceManifestSha256: MANIFEST_SHA256,
      rpcUrl: "https://rpc.example.test/api-key/secret?key=do-not-persist",
      expectedAuthority: EXPECTED_AUTHORITY,
      fetchImpl: fixture.fetchImpl,
      observedAt: "2026-09-19T00:00:00.000Z",
    });
    expect(evidence.verification).toMatchObject({
      status: "verified",
      rpcOrigin: "https://rpc.example.test",
      commitment: "finalized",
      expectedAuthority: EXPECTED_AUTHORITY,
      firstReadContextSlot: "900",
      secondReadContextSlot: "901",
    });
    expect(evidence.sourceManifest).toMatchObject({
      schemaVersion: 2,
      sha256: MANIFEST_SHA256,
      environment: "devnet",
      cluster: "devnet",
      declaredRpcOrigin: null,
    });
    expect(evidence.programs.basket).toMatchObject({
      programDataAddress: fixture.programData.basket,
      upgradeAuthority: EXPECTED_AUTHORITY,
      programDataSlot: "18446744073709551615",
      programDataMetadataLength: 45,
      programDataLength: 4,
    });
    expect(evidence.whitelistConfig).toMatchObject({
      address: WHITELIST_CONFIG_PDA,
      authority: EXPECTED_AUTHORITY,
      pendingAuthority: null,
    });
    expect(fixture.calls).toHaveLength(2);
    expect(fixture.calls.every((call) => call.method === "getMultipleAccounts")).toBe(true);
    expect(fixture.calls.every((call) => JSON.stringify(call.params).includes("finalized"))).toBe(true);
    expect(JSON.stringify(evidence)).not.toContain("api-key");
    expect(JSON.stringify(evidence)).not.toContain("do-not-persist");
    if (!validateEvidence(evidence)) {
      throw new Error(`deployment verification schema rejected evidence: ${JSON.stringify(validateEvidence.errors)}`);
    }
  });

  it("requires the expected authority and never turns discovery into proof", async () => {
    const fixture = makeRpcFixture({ programAuthority: key(230) });
    await expect(verifyManifestAccounts({
      manifest: fixtureManifest(),
      sourceManifestSha256: MANIFEST_SHA256,
      rpcUrl: "https://rpc.example.test",
      expectedAuthority: EXPECTED_AUTHORITY,
      fetchImpl: fixture.fetchImpl,
      observedAt: "2026-09-19T00:00:00.000Z",
    })).rejects.toThrow("upgrade authority mismatch");
  });

  it("binds evidence to a v2 manifest hash and the declared RPC origin", async () => {
    const fixture = makeRpcFixture();
    await expect(verifyManifestAccounts({
      manifest: fixtureManifest(),
      sourceManifestSha256: "",
      rpcUrl: "https://rpc.example.test",
      expectedAuthority: EXPECTED_AUTHORITY,
      fetchImpl: fixture.fetchImpl,
    })).rejects.toThrow("manifest SHA-256");

    const wrongOrigin = fixtureManifest();
    wrongOrigin.deployment.rpcUrl = "https://other-rpc.example.test/private-key";
    await expect(verifyManifestAccounts({
      manifest: wrongOrigin,
      sourceManifestSha256: MANIFEST_SHA256,
      rpcUrl: "https://rpc.example.test",
      expectedAuthority: EXPECTED_AUTHORITY,
      fetchImpl: fixture.fetchImpl,
    })).rejects.toThrow("does not match verifier RPC origin");

    const wrongProgram = fixtureManifest();
    wrongProgram.programs.basket.programId = key(199);
    await expect(verifyManifestAccounts({
      manifest: wrongProgram,
      sourceManifestSha256: MANIFEST_SHA256,
      rpcUrl: "https://rpc.example.test",
      expectedAuthority: EXPECTED_AUTHORITY,
      fetchImpl: fixture.fetchImpl,
    })).rejects.toThrow("canonical Basalt address");
  });

  it("rejects a stale per-program deployed-slot declaration", async () => {
    const fixture = makeRpcFixture();
    const manifest = fixtureManifest();
    manifest.programs.basket.deployedSlot = 123;
    await expect(verifyManifestAccounts({
      manifest,
      sourceManifestSha256: MANIFEST_SHA256,
      rpcUrl: "https://rpc.example.test",
      expectedAuthority: EXPECTED_AUTHORITY,
      fetchImpl: fixture.fetchImpl,
    })).rejects.toThrow("declared deployed slot");
  });

  it("rejects pending whitelist transfers", async () => {
    const fixture = makeRpcFixture({ pending: key(231) });
    await expect(verifyManifestAccounts({
      manifest: fixtureManifest(),
      sourceManifestSha256: MANIFEST_SHA256,
      rpcUrl: "https://rpc.example.test",
      expectedAuthority: EXPECTED_AUTHORITY,
      fetchImpl: fixture.fetchImpl,
    })).rejects.toThrow("pending authority");
  });

  it("rejects loader owner, executable, pointer, and missing account mismatches", async () => {
    const cases = [
      {
        label: "loader owner",
        mutate: (fixture: ReturnType<typeof makeRpcFixture>) => {
          const original = fixture.fetchImpl;
          fixture.fetchImpl = async (url, options) => {
            const response = await original(url, options);
            const body = JSON.parse(options.body) as { params: unknown[] };
            if ((body.params[0] as string[]).includes(BASKET_PROGRAM_ID)) {
              const json = await response.json();
              json.result.value[0].owner = WHITELIST_PROGRAM_ID;
              return { ...response, json: async () => json };
            }
            return response;
          };
        },
        error: "owner mismatch",
      },
      {
        label: "executable",
        mutate: (fixture: ReturnType<typeof makeRpcFixture>) => {
          const original = fixture.fetchImpl;
          fixture.fetchImpl = async (url, options) => {
            const response = await original(url, options);
            const body = JSON.parse(options.body) as { params: unknown[] };
            if ((body.params[0] as string[]).includes(BASKET_PROGRAM_ID)) {
              const json = await response.json();
              json.result.value[0].executable = false;
              return { ...response, json: async () => json };
            }
            return response;
          };
        },
        error: "not executable",
      },
      {
        label: "ProgramData pointer",
        mutate: (fixture: ReturnType<typeof makeRpcFixture>) => {
          const original = fixture.fetchImpl;
          fixture.fetchImpl = async (url, options) => {
            const response = await original(url, options);
            const body = JSON.parse(options.body) as { params: unknown[] };
            const addresses = body.params[0] as string[];
            if (addresses.length > 3 && addresses.includes(BASKET_PROGRAM_ID)) {
              const json = await response.json();
              json.result.value[0] = account(concat(u32(2), pubkeyBytes(key(201))), BPF_UPGRADEABLE_LOADER_ID, true);
              return { ...response, json: async () => json };
            }
            return response;
          };
        },
        error: "pointer changed",
      },
      {
        label: "missing ProgramData",
        mutate: (fixture: ReturnType<typeof makeRpcFixture>) => {
          const original = fixture.fetchImpl;
          fixture.fetchImpl = async (url, options) => {
            const response = await original(url, options);
            const body = JSON.parse(options.body) as { params: unknown[] };
            if ((body.params[0] as string[]).length > 3) {
              const json = await response.json();
              json.result.value[3] = null;
              return { ...response, json: async () => json };
            }
            return response;
          };
        },
        error: "missing",
      },
    ];
    for (const testCase of cases) {
      const fixture = makeRpcFixture();
      testCase.mutate(fixture);
      await expect(verifyManifestAccounts({
        manifest: fixtureManifest(),
        sourceManifestSha256: MANIFEST_SHA256,
        rpcUrl: "https://rpc.example.test",
        expectedAuthority: EXPECTED_AUTHORITY,
        fetchImpl: fixture.fetchImpl,
      })).rejects.toThrow(testCase.error);
    }
  });

  it("does not alter an existing sidecar when verification fails", async () => {
    const fixture = makeRpcFixture({ authority: key(232) });
    const directory = mkdtempSync(join(tmpdir(), "basalt-verifier-"));
    const output = join(directory, "evidence.json");
    writeFileSync(output, "existing evidence\n", "utf8");
    await expect(verifyManifestAccounts({
      manifest: fixtureManifest(),
      sourceManifestSha256: MANIFEST_SHA256,
      rpcUrl: "https://rpc.example.test",
      expectedAuthority: EXPECTED_AUTHORITY,
      fetchImpl: fixture.fetchImpl,
    })).rejects.toThrow("authority mismatch");
    expect(readFileSync(output, "utf8")).toBe("existing evidence\n");
  });
});

describe("deployment verifier URL and RPC guards", () => {
  it("redacts paths, queries, and fragments from evidence origins", () => {
    expect(sanitizeRpcOrigin("https://rpc.example.test/v1/secret?api-key=secret#fragment")).toBe("https://rpc.example.test");
    expect(() => assertRpcUrl("https://user:password@rpc.example.test")).toThrow("credentials");
    expect(() => assertRpcUrl("http://rpc.example.test")).toThrow("https");
    expect(() => assertPublicKey("not-a-public-key", "expected authority")).toThrow("invalid");
  });

  it("allows only account-read RPC methods", async () => {
    const calls: string[] = [];
    const client = new JsonRpcClient({
      rpcUrl: "https://rpc.example.test",
      fetchImpl: async (_url, options) => {
        calls.push((JSON.parse(options.body) as { method: string }).method);
        return { ok: true, status: 200, json: async () => ({ jsonrpc: "2.0", id: 1, result: { context: { slot: 1 }, value: [] } }) };
      },
    });
    await expect(client.call("getBalance", [])).rejects.toThrow("not allowed");
    expect(calls).toEqual([]);
  });
});
