import { describe,it,expect } from "vitest";
import { createHash } from "node:crypto";
import { mkdtemp,chmod,rm,realpath } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { Keypair,PublicKey,VersionedTransaction, type AccountInfo } from "@solana/web3.js";
import { TOKEN_2022_PROGRAM_ID } from "@solana/spl-token";
import { pack } from "@solana/spl-token-metadata";
import bs58 from "bs58";
import { DEVNET_OWNER_NAMESPACE,DEVNET_GENESIS_HASH } from "../src/config/programNamespaces";
import { DEVNET_MOCK_TOKENS,DEVNET_FAUCET_PROGRAM_ID,DEVNET_FAUCET_CLAIM_RAW,deriveDevnetFaucetAuthority,deriveDevnetFaucetVault } from "../../app/lib/devnet-faucet";
import { fixtureMetadata } from "../../scripts/xstocks-devnet/profile";
import { createBootstrapPlan as closedBootstrapPlan,validateDeploymentProof,buildBootstrapInstruction,programData,verifyDeployedBytes,verifyFaucetMocks,executeBootstrap,openPrivateRun,LOADER,MAX_SPEND_LAMPORTS,
  type OwnerManifest,type DeploymentProof,type BootstrapRpc,type Journal,type JournalStore } from "../../scripts/devnet-owner-bootstrap";
const sha=(v:Uint8Array)=>createHash("sha256").update(v).digest("hex");
const disc=(name:string)=>createHash("sha256").update(`account:${name}`).digest().subarray(0,8);
const signer=Keypair.fromSeed(Buffer.alloc(32,81)),owner=Keypair.fromSeed(Buffer.alloc(32,82)).publicKey;
const manifest=():OwnerManifest=>({version:1,mode:"devnet-owner-bootstrap-preparation",cluster:"devnet",genesisHash:DEVNET_GENESIS_HASH,owner:owner.toBase58(),treasury:owner.toBase58(),bootstrapAuthority:signer.publicKey.toBase58(),programIds:{whitelist:DEVNET_OWNER_NAMESPACE.programs.whitelist,basket_factory:DEVNET_OWNER_NAMESPACE.programs.factory,basket:DEVNET_OWNER_NAMESPACE.programs.basket},ownerRoleAcceptance:"accepted",governance:{kind:"single-owner-devnet-only",multisig:false,productionApproval:false},deploymentExecuted:false,sourceCommit:"a".repeat(40),releaseTag:"devnet-owner-test",treasuryAcceptance:"accepted",ownerAcceptanceReference:"test-review:owner-and-treasury"});
const source="a".repeat(40);
// Synthetic signer policy is explicitly injected only into isolated tests, never the CLI.
const createBootstrapPlan=(record:unknown,commit:string)=>closedBootstrapPlan(record,commit,{policy:manifest()});
const plan=()=>createBootstrapPlan(manifest(),source);
function elf(){const b=Buffer.alloc(1024);b.set([127,69,76,70,2,1,1]);b.writeUInt16LE(3,16);b.writeUInt16LE(263,18);b.writeBigUInt64LE(512n,24);b.writeBigUInt64LE(64n,32);b.writeUInt16LE(56,54);b.writeUInt16LE(1,56);b.writeUInt32LE(1,64);b.writeUInt32LE(1,68);b.writeBigUInt64LE(512n,72);b.writeBigUInt64LE(512n,80);b.writeBigUInt64LE(128n,96);b.writeBigUInt64LE(128n,104);return b;}
function proof():DeploymentProof{return {version:1,mode:"devnet-owner-deployment-proof",cluster:"devnet",genesisHash:DEVNET_GENESIS_HASH,sourceCommit:source,feature:"owner-devnet",bootstrapAuthority:signer.publicKey.toBase58(),owner:owner.toBase58(),programs:Object.fromEntries(Object.entries(manifest().programIds).map(([role,id])=>[role,{programId:id,programData:programData(new PublicKey(id)).toBase58(),elfSha256:sha(elf()),elfBytes:1024,deployedSlot:"10"}])) as DeploymentProof["programs"]};}
const info=(data:Buffer,owner:PublicKey,executable=false):AccountInfo<Buffer>=>({data,owner,executable,lamports:1_000_000,rentEpoch:0});
function loader(program:string){const b=Buffer.alloc(36);b.writeUInt32LE(2);programData(new PublicKey(program)).toBuffer().copy(b,4);return info(b,LOADER,true);}
function deployed(){const b=Buffer.alloc(45+1024+32);b.writeUInt32LE(3);b.writeBigUInt64LE(10n,4);b[12]=1;signer.publicKey.toBuffer().copy(b,13);elf().copy(b,45);return info(b,LOADER);}
function tlv(type:number,bytes:Buffer){const h=Buffer.alloc(4);h.writeUInt16LE(type);h.writeUInt16LE(bytes.length,2);return Buffer.concat([h,bytes]);}
function mockAccounts(){const result:AccountInfo<Buffer>[]=[loader(DEVNET_FAUCET_PROGRAM_ID.toBase58())];
 for(const token of DEVNET_MOCK_TOKENS){const authority=signer.publicKey,base=Buffer.alloc(166);base.writeUInt32LE(1);authority.toBuffer().copy(base,4);base.writeBigUInt64LE(1_000_000_000_000n,36);base[44]=8;base[45]=1;base.writeUInt32LE(1,46);authority.toBuffer().copy(base,50);base[165]=1;
  const scale=Buffer.alloc(56);authority.toBuffer().copy(scale);scale.writeDoubleLE(token.multiplier,32);scale.writeDoubleLE(token.multiplier,48);
  const confidential=Buffer.alloc(65);authority.toBuffer().copy(confidential);
  const mint=Buffer.concat([base,tlv(18,Buffer.concat([authority.toBuffer(),token.mint.toBuffer()])),tlv(12,authority.toBuffer()),tlv(6,Buffer.from([1])),tlv(25,scale),tlv(26,Buffer.concat([authority.toBuffer(),Buffer.from([0])])),tlv(4,confidential),tlv(14,Buffer.concat([authority.toBuffer(),Buffer.alloc(32)])),tlv(19,Buffer.from(pack(fixtureMetadata(token.mint,authority,token.letter))))]);
  const vault=Buffer.alloc(165);token.mint.toBuffer().copy(vault);deriveDevnetFaucetAuthority().toBuffer().copy(vault,32);vault.writeBigUInt64LE(DEVNET_FAUCET_CLAIM_RAW*2n,64);vault[108]=1;
  result.push(info(mint,TOKEN_2022_PROGRAM_ID),info(vault,TOKEN_2022_PROGRAM_ID));
 }return result;
}
function whitelist(count:number,pending=false){const b=Buffer.alloc(78);disc("WhitelistConfig").copy(b);signer.publicKey.toBuffer().copy(b,8);b[40]=pending?1:0;if(pending)owner.toBuffer().copy(b,41);const at=pending?73:41;b.writeUInt32LE(count,at);b[at+4]=PublicKey.findProgramAddressSync([Buffer.from("config")],new PublicKey(DEVNET_OWNER_NAMESPACE.programs.whitelist))[1];return info(b,new PublicKey(DEVNET_OWNER_NAMESPACE.programs.whitelist));}
function factory(){const b=Buffer.alloc(89);disc("FactoryConfig").copy(b);signer.publicKey.toBuffer().copy(b,8);owner.toBuffer().copy(b,40);[9000,300,100,300].forEach((n,i)=>b.writeUInt16LE(n,72+i*2));b[88]=PublicKey.findProgramAddressSync([Buffer.from("factory")],new PublicKey(DEVNET_OWNER_NAMESPACE.programs.factory))[1];return info(b,new PublicKey(DEVNET_OWNER_NAMESPACE.programs.factory));}
function admission(index:number){const token=DEVNET_MOCK_TOKENS[index],label=Buffer.from(`mock:${token.symbol}`),b=Buffer.alloc(119);disc("WhitelistedMint").copy(b);token.mint.toBuffer().copy(b,8);b[40]=8;b.writeBigUInt64LE(1_000_000n,41);b.writeUInt32LE(label.length,50);label.copy(b,54);b[54+label.length]=PublicKey.findProgramAddressSync([Buffer.from("mint"),token.mint.toBuffer()],new PublicKey(DEVNET_OWNER_NAMESPACE.programs.whitelist))[1];return info(b,new PublicKey(DEVNET_OWNER_NAMESPACE.programs.whitelist));}
function harness(){let stored:Journal|null=null,step=0,loads=0,sends=0,writes=0;const statuses=new Map<string,unknown>();
 const raw:Array<AccountInfo<Buffer>|null>=[...Object.values(manifest().programIds).map(loader),deployed(),deployed(),deployed(),null,null,null,null,null,null,...mockAccounts()];
 const store:JournalStore={async read(){return structuredClone(stored);},async write(value){writes++;stored=structuredClone(value);}};
 const rpc:BootstrapRpc={async getGenesisHash(){return DEVNET_GENESIS_HASH;},async getMultipleAccountsInfoAndContext(keys){expect(keys).toHaveLength(21);return {context:{slot:100},value:raw};},async getBalance(){return 100_000_000;},async getMinimumBalanceForRentExemption(){return 1_000_000;},async getLatestBlockhash(){return {blockhash:PublicKey.default.toBase58(),lastValidBlockHeight:500};},async getFeeForMessage(){return {value:5000};},async simulateTransaction(){return {value:{err:null}};},async sendRawTransaction(bytes){sends++;const tx=VersionedTransaction.deserialize(bytes),sig=bs58.encode(tx.signatures[0]);expect(stored?.steps[plan().steps[step]].signature).toBe(sig);
  if(step===0)raw[6]=whitelist(0);else if(step===1)raw[7]=factory();else if(step<6){raw[8+step-2]=admission(step-2);raw[6]=whitelist(step-1);}else raw[6]=whitelist(4,true);
  step++;statuses.set(sig,{confirmationStatus:"finalized",err:null});return sig;},async getSignatureStatuses(signatures){return {value:signatures.map(sig=>(statuses.get(sig)??null) as any)};}};
 return {rpc,store,raw,statuses,get stored(){return stored;},get sends(){return sends;},get writes(){return writes;},get loads(){return loads;},async loadSigner(){loads++;return signer;}};
}

describe("devnet-owner bootstrap boundary",()=>{
 it("plans a pending owner manifest offline and refuses execution before RPC/key access",async()=>{const h=harness(),pending={...manifest(),treasury:null,ownerRoleAcceptance:"pending" as const,treasuryAcceptance:"pending" as const};const p=createBootstrapPlan(pending,source);expect(p.blocked).toHaveLength(3);await expect(executeBootstrap({plan:p,proof:proof(),...h})).rejects.toThrow(/acceptance/);expect(h.loads).toBe(0);expect(h.sends).toBe(0);});
 it.each(["genesis","role","treasury","private","governance"])("rejects forged %s manifest",kind=>{const m:any=manifest();if(kind==="genesis")m.genesisHash="mainnet";if(kind==="role")m.programIds.basket=m.programIds.whitelist;if(kind==="treasury")m.treasury=PublicKey.default.toBase58();if(kind==="private")m.secretKey=[1,2,3];if(kind==="governance")m.governance.productionApproval=true;expect(()=>createBootstrapPlan(m,source)).toThrow();});
 it("pins default production owner/bootstrap and refuses substituted roles or incomplete public acceptance",()=>{
  expect(()=>closedBootstrapPlan(manifest(),source)).toThrow(/source-controlled/);
  for(const field of ["owner","bootstrapAuthority"]){const m:any=manifest();m[field]=Keypair.fromSeed(Buffer.alloc(32,90)).publicKey.toBase58();expect(()=>createBootstrapPlan(m,source)).toThrow(/source-controlled/);}
  for(const edit of [(m:any)=>m.treasury=m.bootstrapAuthority,(m:any)=>m.ownerAcceptanceReference=null,(m:any)=>m.sourceCommit="b".repeat(40),(m:any)=>m.deploymentExecuted=true,(m:any)=>m.policy={}]){const m:any=manifest();edit(m);expect(()=>createBootstrapPlan(m,source)).toThrow();}
  const pending=createBootstrapPlan({...manifest(),treasuryAcceptance:"pending"},source);expect(pending.blocked).toEqual(["Public review prerequisite pending: treasuryAcceptance"]);
 });
 it("binds source feature, bootstrap authority and every canonical deployed role",()=>{for(const mutation of [(p:any)=>p.sourceCommit="b".repeat(40),(p:any)=>p.feature="legacy",(p:any)=>p.bootstrapAuthority=owner.toBase58(),(p:any)=>p.programs.basket.programData=owner.toBase58()]){const p=proof();mutation(p);expect(()=>validateDeploymentProof(p,plan())).toThrow();}});
 it("uses init-only readonly loader guards, fixed9000 split and four fixed mint accounts",()=>{for(const step of ["init-whitelist","init-factory"]){const ix=buildBootstrapInstruction(plan(),step);expect(ix.keys).toHaveLength(5);expect(ix.keys[3]).toMatchObject({isWritable:false,isSigner:false});expect(ix.keys[4].pubkey.equals(programData(ix.programId))).toBe(true);}const factoryIx=buildBootstrapInstruction(plan(),"init-factory");expect(factoryIx.data.readUInt16LE(40)).toBe(9000);expect(factoryIx.data.subarray(8,40).equals(owner.toBuffer())).toBe(true);DEVNET_MOCK_TOKENS.forEach(token=>expect(buildBootstrapInstruction(plan(),`admit-${token.symbol}`).keys[2].pubkey.equals(token.mint)).toBe(true));expect(()=>buildBootstrapInstruction(plan(),"admit-AAPLx")).toThrow();expect(buildBootstrapInstruction(plan(),"propose-whitelist-owner").keys).toHaveLength(2);});
 it.each(["authority","pointer","padding","hash","entrypoint"])("rejects invalid deployed %s before loading signer",kind=>{const a=proof().programs.basket,p=loader(a.programId),d=deployed();if(kind==="authority")owner.toBuffer().copy(d.data,13);if(kind==="pointer")owner.toBuffer().copy(p.data,4);if(kind==="padding")d.data[d.data.length-1]=1;if(kind==="hash")d.data[45+600]^=1;if(kind==="entrypoint")d.data.writeBigUInt64LE(0n,45+24);expect(()=>verifyDeployedBytes(p,d,a,signer.publicKey.toBase58())).toThrow();});
 it("requires actual full-profile initialized faucet mocks, mint identity, multiplier and funded vault",()=>{expect(()=>verifyFaucetMocks(mockAccounts())).not.toThrow();for(const mutate of [(a:any[])=>a[1].owner=LOADER,(a:any[])=>a[1].data[44]=6,(a:any[])=>a[2].data[108]=2,(a:any[])=>a[2].data.writeBigUInt64LE(0n,64),(a:any[])=>owner.toBuffer().copy(a[2].data,32)]){const a=mockAccounts();mutate(a);expect(()=>verifyFaucetMocks(a)).toThrow();}});
 it("executes exactly seven simulated single-send steps, leaves owner claim and loader handoff unexecuted, then idempotently rechecks",async()=>{const h=harness();const result=await executeBootstrap({plan:plan(),proof:proof(),...h});expect(h.sends).toBe(7);expect(h.loads).toBe(1);expect(result.spentBudget).toBeLessThan(MAX_SPEND_LAMPORTS);expect(Object.values(result.steps).every(r=>r.status==="finalized")).toBe(true);expect(h.raw[6]?.data[40]).toBe(1);await executeBootstrap({plan:plan(),proof:proof(),...h});expect(h.sends).toBe(7);expect(h.loads).toBe(1);});
 it("never loads the signer for wrong network, deployed bytes or inadequate funding",async()=>{for(const mode of ["network","bytes","funding"]){const h=harness();if(mode==="network")h.rpc.getGenesisHash=async()=>"wrong";if(mode==="bytes")h.raw[3]!.data[13]^=1;if(mode==="funding")h.rpc.getBalance=async()=>0;await expect(executeBootstrap({plan:plan(),proof:proof(),...h})).rejects.toThrow();expect(h.loads).toBe(0);expect(h.sends).toBe(0);}});
 it("simulation failure and failed pre-send receipt persistence produce zero submissions",async()=>{for(const mode of ["simulation","receipt"]){const h=harness();if(mode==="simulation")h.rpc.simulateTransaction=async()=>({value:{err:{InstructionError:[0,"Unauthorized"]}}});else{const write=h.store.write;h.store.write=async value=>{if(Object.keys(value.steps).length)throw new Error("disk full");await write(value);};}await expect(executeBootstrap({plan:plan(),proof:proof(),...h})).rejects.toThrow();expect(h.sends).toBe(0);}});
 it("persists the exact signature before transport uncertainty and never resends ambiguous submissions",async()=>{const h=harness();h.rpc.sendRawTransaction=async()=>{throw new Error("transport uncertain");};await expect(executeBootstrap({plan:plan(),proof:proof(),...h})).rejects.toThrow("transport uncertain");expect(Object.values(h.stored!.steps)).toHaveLength(1);let retried=0;h.rpc.sendRawTransaction=async()=>{retried++;return "forbidden";};await expect(executeBootstrap({plan:plan(),proof:proof(),...h})).rejects.toThrow(/ambiguous/);expect(retried).toBe(0);});
 it("recovers an uncertain finalized receipt using the same signature without replay",async()=>{const h=harness(),send=h.rpc.sendRawTransaction;h.rpc.sendRawTransaction=async(bytes,opts)=>{await send(bytes,opts);throw new Error("response lost");};await expect(executeBootstrap({plan:plan(),proof:proof(),...h})).rejects.toThrow("response lost");expect(h.sends).toBe(1);h.rpc.sendRawTransaction=send;await executeBootstrap({plan:plan(),proof:proof(),...h});expect(h.sends).toBe(7);});
 it("rejects altered private identity and contradictory existing singletons before any send",async()=>{const h=harness();await h.store.write({version:1,manifestHash:"wrong",proofHash:"wrong",sourceCommit:source,bootstrapAuthority:signer.publicKey.toBase58(),initialBalance:100_000_000,spentBudget:0,steps:{}});await expect(executeBootstrap({plan:plan(),proof:proof(),...h})).rejects.toThrow(/identity/);expect(h.loads).toBe(0);const other=harness();other.raw[7]=factory();owner.toBuffer().copy(other.raw[7]!.data,8);await expect(executeBootstrap({plan:plan(),proof:proof(),...other})).rejects.toThrow(/Factory/);expect(other.sends).toBe(0);});
 it("enforces private directory mode, dedicated path, exclusive lock and durable receipt isolation without loading keys",async()=>{const dir=await realpath(await mkdtemp(join(tmpdir(),"basalt-devnet-owner-test-")));await chmod(dir,0o700);try{const run=await openPrivateRun(dir);await expect(openPrivateRun(dir)).rejects.toThrow();const journal:Journal={version:1,manifestHash:"m",proofHash:"p",sourceCommit:source,bootstrapAuthority:signer.publicKey.toBase58(),initialBalance:1,spentBudget:0,steps:{}};await run.store.write(journal);expect(await run.store.read()).toEqual(journal);await run.close();await chmod(dir,0o755);await expect(openPrivateRun(dir)).rejects.toThrow(/mode0700/);}finally{await rm(dir,{recursive:true,force:true});}});
});
