/**
 * api/auth.ts — wallet-signature auth for the SOCIAL WRITE surface only.
 *
 * This is the backend's first authenticated surface, and its scope is
 * deliberately narrow: profiles, follows, posts, likes, comments. Nothing
 * here touches funds or transactions — the backend still never signs or
 * submits Solana txs (AGENTS.md §2 #5). The flow is SIWS-lite:
 *
 *   1. client POST /auth/nonce {wallet}          → single-use nonce (5 min TTL)
 *   2. client signs the EXACT message (wallet adapter signMessage):
 *        Basalt Social\nWallet: <wallet>\nNonce: <nonce>
 *   3. client POST /auth/verify {wallet, nonce, signature(base58 ed25519)}
 *      → HMAC token `v1.<b64url payload>.<b64url hmac>` (7 days)
 *   4. later writes carry `Authorization: Bearer <token>`
 *
 * Nonces live in a process-local Map (single-instance backend, same lifecycle
 * as the in-memory quote/NAV caches); token verification is stateless.
 */
import crypto from "node:crypto";
import nacl from "tweetnacl";
import bs58 from "bs58";

export const AUTH_MESSAGE_PREFIX = "Basalt Social";
export const TOKEN_TTL_SECONDS = 7 * 24 * 3600;
export const NONCE_TTL_MS = 5 * 60 * 1000;

const DEV_FALLBACK_SECRET = "basalt-dev-social-secret-do-not-use-in-prod";
const SECRET_PLACEHOLDER = /(?:change[-_ ]?me|replace[-_ ]?me|your[-_ ]?secret|do[-_ ]?not[-_ ]?use[-_ ]?in[-_ ]?prod|test[-_ ]?only|placeholder|example)/i;
let ephemeralDevSecret: string | undefined;

/** Validate before starting workers/listening; never include the configured value in errors. */
export function socialAuthSecret(): string {
  const secret = process.env.SOCIAL_AUTH_SECRET?.trim();
  if (secret) {
    if (Buffer.byteLength(secret, "utf8") < 32 || secret === DEV_FALLBACK_SECRET || SECRET_PLACEHOLDER.test(secret)) {
      throw new Error("SOCIAL_AUTH_SECRET must contain at least 32 generated bytes and must not be a placeholder");
    }
    return secret;
  }
  if (process.env.NODE_ENV !== "production" && process.env.SOCIAL_AUTH_ALLOW_DEV_SECRET === "1") {
    // Explicit local-only opt-in. A restart invalidates tokens; no published fallback key exists.
    ephemeralDevSecret ??= crypto.randomBytes(32).toString("hex");
    return ephemeralDevSecret;
  }
  throw new Error("SOCIAL_AUTH_SECRET is required; local development may explicitly set SOCIAL_AUTH_ALLOW_DEV_SECRET=1");
}

/** The exact bytes a wallet must sign — shared by verify and client-side tests. */
export function buildAuthMessage(wallet: string, nonce: string): string {
  return `${AUTH_MESSAGE_PREFIX}\nWallet: ${wallet}\nNonce: ${nonce}`;
}

export function isValidWalletPubkey(s: string): boolean {
  if (typeof s !== "string" || s.length < 32 || s.length > 44) return false;
  try {
    const bytes = bs58.decode(s);
    return bytes.length === 32;
  } catch {
    return false;
  }
}

// --- nonce store ---------------------------------------------------------------

export const MAX_PENDING_NONCES = 10_000;
export const MAX_PENDING_NONCES_PER_WALLET = 3;

export class AuthRateLimitError extends Error {
  readonly status = 429;
  readonly code = "AUTH_RATE_LIMITED";
  readonly retryAfterSeconds: number;

  constructor(message: string, expiresAt: number, nowMs: number) {
    super(message);
    this.name = "AuthRateLimitError";
    this.retryAfterSeconds = Math.max(1, Math.ceil((expiresAt - nowMs) / 1000));
  }
}

interface NonceEntry {
  wallet: string;
  expiresAt: number;
}

const nonces = new Map<string, NonceEntry>(); // insertion order is expiry order
const walletNonces = new Map<string, Set<string>>();
let lastIssuedAt = 0;

function removeNonce(key: string, entry: NonceEntry): void {
  nonces.delete(key);
  const keys = walletNonces.get(entry.wallet);
  keys?.delete(key);
  if (keys?.size === 0) walletNonces.delete(entry.wallet);
}

/** Remove only the expired prefix. Each expired entry is removed once; fresh entries never require a full-map sweep. */
function expireNonces(nowMs: number): void {
  for (const [key, entry] of nonces) {
    if (entry.expiresAt > nowMs) break;
    removeNonce(key, entry);
  }
}

export function issueNonce(wallet: string, nowMs: number = Date.now()): { nonce: string; expiresAt: string } {
  expireNonces(nowMs);
  const walletKeys = walletNonces.get(wallet);
  if (walletKeys && walletKeys.size >= MAX_PENDING_NONCES_PER_WALLET) {
    const first = nonces.get(walletKeys.values().next().value!)!;
    throw new AuthRateLimitError("too many pending nonces for this wallet", first.expiresAt, nowMs);
  }
  if (nonces.size >= MAX_PENDING_NONCES) {
    const first = nonces.values().next().value!;
    throw new AuthRateLimitError("authentication nonce capacity reached", first.expiresAt, nowMs);
  }
  // Keep expiry ordering if the system wall clock moves backward.
  lastIssuedAt = Math.max(lastIssuedAt, nowMs);
  const expiresAt = lastIssuedAt + NONCE_TTL_MS;
  const nonce = crypto.randomBytes(16).toString("hex");
  const key = `${wallet}:${nonce}`;
  nonces.set(key, { wallet, expiresAt });
  if (walletKeys) walletKeys.add(key);
  else walletNonces.set(wallet, new Set([key]));
  return { nonce, expiresAt: new Date(expiresAt).toISOString() };
}

/** Unknown, expired and consumed nonces all fail; consumption releases capacity immediately. */
export function consumeNonce(wallet: string, nonce: string, nowMs: number = Date.now()): boolean {
  expireNonces(nowMs);
  const key = `${wallet}:${nonce}`;
  const entry = nonces.get(key);
  if (!entry) return false;
  removeNonce(key, entry);
  return entry.expiresAt > nowMs;
}

/** Test hook — clears the bounded nonce store and its wallet accounting. */
export function clearNonces(): void {
  nonces.clear();
  walletNonces.clear();
  lastIssuedAt = 0;
}

// --- tokens --------------------------------------------------------------------

function b64url(buf: Buffer): string {
  return buf.toString("base64url");
}

export interface TokenPayload {
  wallet: string;
  exp: number; // unix seconds
}

export function signToken(wallet: string, secret: string, nowMs: number = Date.now()): { token: string; expiresAt: string } {
  const payload: TokenPayload = { wallet, exp: Math.floor(nowMs / 1000) + TOKEN_TTL_SECONDS };
  const body = b64url(Buffer.from(JSON.stringify(payload), "utf8"));
  const mac = b64url(crypto.createHmac("sha256", secret).update(body).digest());
  return { token: `v1.${body}.${mac}`, expiresAt: new Date(payload.exp * 1000).toISOString() };
}

export function verifyToken(token: string, secret: string, nowMs: number = Date.now()): TokenPayload | null {
  if (typeof token !== "string") return null;
  const parts = token.split(".");
  if (parts.length !== 3 || parts[0] !== "v1") return null;
  const [, body, mac] = parts;
  const expected = crypto.createHmac("sha256", secret).update(body).digest();
  let macBuf: Buffer;
  try {
    macBuf = Buffer.from(mac, "base64url");
  } catch {
    return null;
  }
  if (macBuf.length !== expected.length || !crypto.timingSafeEqual(macBuf, expected)) return null;
  let payload: TokenPayload;
  try {
    const parsed = JSON.parse(Buffer.from(body, "base64url").toString("utf8")) as TokenPayload;
    if (typeof parsed.wallet !== "string" || typeof parsed.exp !== "number") return null;
    payload = parsed;
  } catch {
    return null;
  }
  if (payload.exp * 1000 <= nowMs) return null;
  return payload;
}

/** Extract + verify the bearer token from an Authorization header (or null). */
export function walletFromAuthHeader(header: string | undefined, secret: string, nowMs: number = Date.now()): string | null {
  if (!header) return null;
  const match = /^Bearer\s+(.+)$/i.exec(header.trim());
  if (!match) return null;
  const payload = verifyToken(match[1], secret, nowMs);
  return payload ? payload.wallet : null;
}

/**
 * Verify an ed25519 signature (base58) over the exact auth message.
 * Wallet adapters sign UTF-8 bytes of the displayed message.
 */
export function verifyWalletSignature(wallet: string, nonce: string, signatureBase58: string): boolean {
  if (!isValidWalletPubkey(wallet) || typeof signatureBase58 !== "string" ||
      signatureBase58.length < 64 || signatureBase58.length > 88) return false;
  let sig: Uint8Array;
  try {
    sig = bs58.decode(signatureBase58);
  } catch {
    return false;
  }
  if (sig.length !== nacl.sign.signatureLength) return false;
  const message = Buffer.from(buildAuthMessage(wallet, nonce), "utf8");
  return nacl.sign.detached.verify(message, sig, bs58.decode(wallet));
}
